@extends('layouts.public')
@section('title','Profil Pendidikan Ma’had Aly Salafiyah Syafi’iyah Situbondo')
@section('description','Mengenal Ma’had Aly Salafiyah Syafi’iyah Sukorejo Situbondo, pendidikan tinggi pesantren dengan takhassus fikih dan usul fikih.')
@section('content')
<div class="wrap institution-page">
    <div class="breadcrumbs"><a href="{{ route('home') }}">Beranda</a><span>/</span><span>Profil pendidikan</span></div>
    <header class="institution-hero">
        <div><span class="eyebrow">MA’HAD ALY SALAFIYAH SYAFI’IYAH SITUBONDO</span><h1>Ilmu yang berakar.<br><em>Khidmah yang meluas.</em></h1><p>Pendidikan tinggi pesantren di lingkungan Pondok Pesantren Salafiyah Syafi’iyah Sukorejo, Situbondo, dengan perhatian pada pendalaman fikih dan usul fikih.</p><a class="button" href="#pendidikan">Mengenal pendidikan <x-icon name="arrow"/></a></div>
        <div class="institution-emblem" aria-hidden="true"><span class="emblem-top">MA’HAD ALY</span><x-icon name="book"/><span class="emblem-arabic" lang="ar" dir="rtl">المعهد العالي</span><span class="emblem-bottom">SUKOREJO · SITUBONDO</span></div>
    </header>
    <dl class="institution-facts"><div><dt>Lingkungan pendidikan</dt><dd>Pesantren Sukorejo</dd></div><div><dt>Takhassus keilmuan</dt><dd>Fikih & usul fikih</dd></div><div><dt>Lokasi</dt><dd>Situbondo, Jawa Timur</dd></div></dl>
    <section class="institution-intro" id="pendidikan" aria-labelledby="education-title"><div><span class="eyebrow">PROFIL PENDIDIKAN</span><h2 id="education-title">Mendalami ilmu,<br>membaca kehidupan.</h2></div><div><p>Ma’had Aly Salafiyah Syafi’iyah merupakan bagian dari lingkungan pendidikan Pesantren Sukorejo. Takhassusnya menempatkan fikih dan usul fikih sebagai pusat pendalaman ilmu.</p><p>Dalam daftar program studi PBSB Kementerian Agama, Ma’had Aly Salafiyah Syafi’iyah Situbondo tercatat pada jenjang S1 dengan program Fiqh dan Ushul Fiqh. Informasi akademik dan penerimaan terkini dapat diikuti melalui kanal resmi lembaga.</p></div></section>
    <div class="education-grid">
        <section class="education-card"><span class="education-number">01 / BIDANG KAJIAN</span><x-icon name="book"/><h3>Fikih</h3><p>Pendalaman hukum Islam yang berkaitan dengan ibadah, muamalah, dan kehidupan masyarakat. Sebuah ruang belajar untuk memahami persoalan beserta rujukannya.</p><a href="{{ route('channel','fiqih-kontemporer') }}">Baca kajian fiqih <x-icon name="arrow"/></a></section>
        <section class="education-card"><span class="education-number">02 / LANDASAN METODOLOGI</span><x-icon name="book"/><h3>Usul fikih</h3><p>Kajian landasan dan metode memahami dalil serta merumuskan hukum. Ketelitian membaca teks berjalan bersama kepekaan terhadap konteks persoalan.</p><a href="{{ route('channel','bahtsul-masail') }}">Jelajahi bahtsul masail <x-icon name="arrow"/></a></section>
    </div>
    <section class="institution-media"><span class="eyebrow">PENDIDIKAN & MEDIA</span><h2>Memperluas manfaat<br>dari ruang keilmuan.</h2><p>Media ini menjadi ruang Ma’had Aly Situbondo untuk menghadirkan kajian fiqih kontemporer, khazanah pesantren, opini, serta kabar pendidikan kepada masyarakat.</p><p>Setiap naskah melewati pemeriksaan redaksi. Kajian hukum dan hasil bahtsul masail memerlukan rujukan serta verifikasi pihak keilmuan yang berwenang.</p><a href="{{ route('page','pedoman') }}">Mengenal proses redaksi <x-icon name="arrow"/></a></section>
    <section class="academic-cta"><div><span class="eyebrow">TERHUBUNG DENGAN LEMBAGA</span><h2>Kenali Ma’had Aly lebih dekat.</h2><p>Informasi penerimaan, persyaratan, jadwal, dan layanan akademik mengikuti pengumuman resmi Ma’had Aly.</p></div><a class="button" href="https://maalysitubondo.ac.id/" target="_blank" rel="noopener noreferrer">Situs resmi Ma’had Aly <x-icon name="external"/><span class="sr"> (tab baru)</span></a></section>
    <details class="profile-sources"><summary>Sumber profil pendidikan</summary><p>Ringkasan identitas dan takhassus merujuk pada kanal kelembagaan berikut. Halaman ini bukan pengumuman penerimaan mahasantri.</p><ul><li><a href="https://maalysitubondo.ac.id/" target="_blank" rel="noopener noreferrer">Situs resmi Ma’had Aly Situbondo (tab baru)</a></li><li><a href="https://sukorejo.com/masyayikh" target="_blank" rel="noopener noreferrer">Pondok Pesantren Salafiyah Syafi’iyah Sukorejo — jaringan lembaga (tab baru)</a></li><li><a href="https://pendaftaran-beasiswa.kemenag.go.id/pbsb/konten/program-studi/Program%2520Studi" target="_blank" rel="noopener noreferrer">Kementerian Agama — program studi PBSB (tab baru)</a></li></ul></details>
</div>
@endsection
