@extends('layouts.public')
@section('title', ['tentang'=>'Tentang & Redaksi','pedoman'=>'Pedoman Kontribusi','privasi'=>'Privasi'][$page].' — Ma’had Aly')
@section('content')<div class="wrap page-space narrow"><span class="eyebrow">RUANG BERSAMA</span>
@if($page==='tentang')<h1>Tentang & redaksi</h1><div class="prose"><p>{{ $settings['about'] }}</p><h2>Susunan redaksi</h2><p class="preserve">{{ $settings['editorial'] }}</p><h2>Hubungi kami</h2><p>{{ $settings['location'] }}, Jawa Timur.</p>@if($settings['email'])<a href="mailto:{{ $settings['email'] }}">{{ $settings['email'] }}</a>@else<p>Alamat kontak akan diumumkan pengelola media.</p>
@endif</div>
@elseif($page==='pedoman')<h1>Menulis bersama kami</h1><div class="prose"><p>Media ini menjadi ruang berbagi kajian fiqih kontemporer, khazanah pesantren, opini, dan kabar Ma’had.</p><h2>Mulai dari gagasan yang jernih</h2><ol><li>Hubungi redaksi untuk mendapatkan akun kontributor.</li><li>Tulis naskah orisinal dengan judul, ringkasan, isi, dan kanal yang sesuai.</li><li>Cantumkan kitab, penulis, edisi, halaman, atau tautan sumber yang bisa diperiksa. Kanal Fiqih Kontemporer dan Bahtsul Masail mewajibkan rujukan.</li><li>Pastikan izin penggunaan gambar dan tulis kredit atau keterangan gambar.</li><li>Simpan draf, periksa pratinjau, lalu kirim ke redaksi.</li></ol><h2>Setiap tulisan melalui review</h2><p>Admin memeriksa substansi, rujukan, bahasa, dan kelayakan tayang. Naskah dapat disetujui, dijadwalkan, dikembalikan untuk revisi, atau ditolak dengan alasan.</p><p>Perubahan naskah yang sudah terbit harus melalui review baru. Hasil bahtsul masail dan keputusan hukum harus mendapat verifikasi pihak keilmuan yang berwenang sebelum diterbitkan.</p><a class="button" href="{{ route('login') }}">Masuk ruang redaksi →</a></div>
@else<h1>Privasi pembaca & kontributor</h1><div class="prose"><p>Situs menyimpan nama, email, kata sandi yang di-hash, naskah, dan riwayat tindakan kontributor untuk menjalankan proses redaksi.</p><h2>Cookie & penyimpanan perangkat</h2><p>Cookie digunakan untuk sesi login dan perlindungan formulir. Aplikasi PWA menyimpan aset antarmuka serta halaman pemberitahuan offline. Naskah privat, halaman redaksi, dan sesi login tidak disimpan dalam cache PWA.</p><h2>Kendali data</h2><p>Hubungi redaksi untuk pembaruan akun, koreksi, atau permintaan penghapusan data. Nama penulis muncul pada artikel publik yang diterbitkan.</p><p>Persetujuan dan publikasi memerlukan koneksi internet. Pengelola VPS dapat menyimpan log teknis untuk pemeliharaan dan keamanan.</p></div>
@endif
</div>@endsection
