@extends('layouts.desk')
@section('title','Editor Naskah')
@section('content')<div class="desk-heading"><div><span class="eyebrow">RUANG MENULIS</span><h1>{{ $revision->exists ? 'Sunting naskah' : 'Gagasan baru' }}</h1></div>@if($revision->exists)<span class="status {{ $revision->status }}">{{ $revision->label() }}</span>@endif</div>
@if($revision->review_note)<div class="notice"><strong>Catatan redaksi</strong><p>{{ $revision->review_note }}</p></div>@endif
@if($revision->exists && !$revision->editable())<div class="notice">Versi ini dikunci untuk menjaga proses persetujuan. <a href="{{ route('preview',$revision) }}">Lihat pratinjau & keputusan →</a></div>@if(in_array($revision->status,['published','superseded']))<form action="{{ route('revise',$article) }}" method="post">@csrf<button class="button">Buat revisi baru</button></form>@endif
@else
<form class="editor-grid" action="{{ $revision->exists ? route('draft.update',$revision) : route('draft.store') }}" method="post" enctype="multipart/form-data" data-editor>@csrf @if($revision->exists)@method('PUT')@endif
<div class="panel stack"><label>Judul artikel<input name="title" value="{{ old('title',$revision->title) }}" minlength="8" maxlength="180" required placeholder="Judul yang jernih dan menarik"></label><label>Ringkasan<textarea name="excerpt" rows="3" minlength="20" maxlength="350" required placeholder="Inti tulisan dalam 1–2 kalimat">{{ old('excerpt',$revision->excerpt) }}</textarea></label><label>Isi naskah <span class="help">Markdown: ## subjudul, **tebal**, > kutipan. Teks Arab didukung.</span><textarea class="body-editor" name="body" dir="auto" rows="20" minlength="50" required placeholder="Mulai menulis di sini…">{{ old('body',$revision->body) }}</textarea></label><small data-word-count></small><label>Rujukan & catatan<textarea name="sources" dir="auto" rows="5" placeholder="Nama kitab/penulis, edisi, halaman, atau URL sumber">{{ old('sources',$revision->sources) }}</textarea><span class="help">Wajib untuk Fiqih Kontemporer dan Bahtsul Masail sebelum dikirim.</span></label></div>
<aside class="stack"><div class="panel stack"><h2>Pengaturan naskah</h2><label>Kanal<select name="category_id" required><option value="">Pilih kanal</option>@foreach($categories as $c)<option value="{{ $c->id }}" @selected(old('category_id',$revision->category_id)==$c->id)>{{ $c->name }}</option>@endforeach</select></label><label>Gambar sampul<input type="file" name="cover" accept="image/jpeg,image/png,image/webp"><span class="help">JPG, PNG, WebP · maksimal 5 MB.</span></label>@if($revision->coverUrl())<img class="editor-cover" src="{{ $revision->coverUrl() }}" alt="Sampul saat ini">@endif<label>Keterangan & kredit gambar<input name="cover_caption" value="{{ old('cover_caption',$revision->cover_caption) }}" maxlength="255"></label><button class="button">Simpan draf</button><small class="help">Simpan sebelum membuka pratinjau atau mengirim ke redaksi.</small>@if($revision->exists)<a class="button outline" href="{{ route('preview',$revision) }}">Pratinjau tersimpan ↗</a>@endif</div><div class="panel help">Naskah tidak langsung tayang. Admin media memeriksa dan menyetujui publikasinya.</div></aside></form>
@if($revision->exists)<form class="submit-row" action="{{ route('submit',$revision) }}" method="post" data-confirm="Kirim versi yang sudah disimpan ke redaksi?">@csrf<button class="button amber">Kirim naskah tersimpan ke redaksi →</button></form>@endif
@endif @endsection
