@extends('layouts.desk')
@section('title','Pratinjau Naskah')
@section('content')<div class="desk-heading"><div><span class="eyebrow">PRATINJAU PRIVAT · VERSI #{{ $revision->id }}</span><h1>Periksa naskah</h1></div><a class="button outline" href="{{ route('editor',$revision) }}">Buka editor</a></div><div class="editor-grid"><article class="panel preview-paper"><span class="status {{ $revision->status }}">{{ $revision->label() }}</span><p class="eyebrow">{{ $revision->category->name }}</p><h1>{{ $revision->title }}</h1><p class="article-deck">{{ $revision->excerpt }}</p><div class="meta">{{ $revision->article->author->name }}</div>@if($revision->coverUrl())<figure><img class="editor-cover" src="{{ $revision->coverUrl() }}" alt="{{ $revision->cover_caption }}"><figcaption>{{ $revision->cover_caption }}</figcaption></figure>
@endif<div class="prose">{!! $revision->html() !!}</div><section class="references"><h2>Rujukan</h2><p class="preserve">{{ $revision->sources ?: 'Belum ada rujukan.' }}</p></section></article><aside class="stack">
@if($revision->review_note)<div class="notice"><strong>Catatan redaksi</strong><p>{{ $revision->review_note }}</p></div>
@endif
@if(auth()->user()->isAdmin() && $revision->status==='pending')<form class="panel stack" action="{{ route('decide',$revision) }}" method="post">@csrf<h2>Keputusan redaksi</h2><label>Keputusan<select name="decision" required><option value="">Pilih keputusan</option><option value="approve">Setujui untuk tayang</option><option value="changes_requested">Minta perbaikan</option><option value="rejected">Tolak naskah</option></select></label><label>Catatan<textarea name="note" rows="4" placeholder="Wajib untuk perbaikan atau penolakan"></textarea></label><label>Jadwal tayang (WIB)<input name="publish_at" type="datetime-local"><small class="help">Kosongkan untuk langsung tayang saat disetujui.</small></label><button class="button">Simpan keputusan</button></form>
@endif
@if($revision->status==='scheduled')<div class="panel"><h2>Jadwal tayang</h2><p>{{ $revision->publish_at->translatedFormat('d F Y H:i') }} WIB</p></div>
@endif
@if(auth()->user()->isAdmin())<div class="panel stack"><form method="post" action="{{ route('feature',$revision->article) }}">@csrf<button class="button outline">{{ $revision->article->featured ? 'Hapus dari' : 'Jadikan' }} pilihan headline</button></form>@if($revision->article->published_revision_id || $revision->status==='scheduled')<form class="stack" action="{{ route('withdraw',$revision->article) }}" method="post" data-confirm="Tarik artikel dari publik dan batalkan jadwalnya?">@csrf<label>Alasan penarikan<input name="note" required minlength="5" maxlength="1000"></label><button class="button danger">Tarik / batalkan tayang</button></form>
@endif</div>
@endif
<div class="panel"><h2>Jejak redaksi</h2><ol class="history">@foreach($history as $log)<li><strong>{{ ['created'=>'Draf dibuat','saved'=>'Draf disimpan','submitted'=>'Dikirim untuk review','approved'=>'Disetujui','published'=>'Diterbitkan','changes_requested'=>'Diminta revisi','rejected'=>'Ditolak','revision_created'=>'Revisi baru','withdrawn'=>'Ditarik'][$log->action] ?? $log->action }}</strong><small>{{ $log->user?->name ?? 'Penjadwal' }} · {{ $log->created_at->format('d/m H:i') }}</small>@if($log->note)<p>{{ $log->note }}</p>
@endif</li>@endforeach</ol></div></aside></div>@endsection
